### ISSUE TITLE
Project Versioning Information

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#21]
As part of our plugin, we are consuming the project text, parsing it, tokenizing it, and storing it into a database.  But that only gets us a current snapshot of the text.  What would help us is to know that on this date, we got version x.x.x.0 of the text.  Tomorrow, we have now have version x.x.x.1 of the text.  Do you have anything like that in Paratext which could be exposed by the API?

Alternatively, there probably is something within the Mercurial file system that we could read in.  But that sounds like a way more painful route to have to go.

**Comment by jwickberg** [comment]
There is no version field that Paratext maintains as project text is
changed - Mercurial history or saving a checksum during your update process
would be the only options I can think of.

Currently, history is not available through the plugin interface, so that
would need to be a change to the interface. I'm not sure when work like
that would be scheduled.

**Comment by GeoDirk** [comment]
Thanks...I assumed as much.  We'll try to figure out a different approach.
