### ISSUE TITLE
SetReferenceForSyncGroup()

### ISSUE THREAD

**Issue by GeoDirk** [ubsicap/paratext_demo_plugins#4]
The host.SetReferenceForSyncGroup() method takes in as its first parameter an IVerseRef.  But I'm not seeing any setters associated with that interface.  There are only getters.  I'm I missing something?

**Comment by FoolRunning** [comment]
I'm assuming you mean that you can't find a way to create a **IVerseRef** instance. It's a little confusing because a verse reference needs a versification to work properly. Because of this, you create the verse reference from the versification (which can be gotten from a [project](https://github.com/ubsicap/paratext_demo_plugins/wiki/IVersification#createreference) or via the [plugin host](https://github.com/ubsicap/paratext_demo_plugins/wiki/IVersification#createreference)) via the [CreateReferece methods](https://github.com/ubsicap/paratext_demo_plugins/wiki/IVersification#createreference).

**Comment by GeoDirk** [comment]
@FoolRunning Yeah that a bit round about way of doing it but it makes sense.  Thanks for the explanation and link!
